### ISSUE TITLE
Train error: 'RecursiveScriptModule' has no attribute 'rvq'

### ISSUE THREAD

**Issue by timmb** [caillonantoine/msprior#1]
Hi Antoine, thanks for this exciting looking model!

I'm trying to train mspriors on a model generated using Rave v2 last week. I'm running in a WSL Docker container.

Preprocess works but the train command gives me an error before it gets going.

My command
```bash
msprior train --config encoder_decoder_continuous --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music --pretrained_embedding /models/RaveV2/r2_tim-music_incomplete.ts   
```

The output:
```
I0515 18:19:04.334935 139662491390080 train.py:49] parsing configuration
I0515 18:19:04.335927 139662491390080 resource_reader.py:50] system_path_file_exists:encoder_decoder_continuous.gin
E0515 18:19:04.336350 139662491390080 resource_reader.py:55] Path not found: encoder_decoder_continuous.gin
I0515 18:19:04.336493 139662491390080 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/encoder_decoder_continuous.gin
E0515 18:19:04.336674 139662491390080 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/encoder_decoder_continuous.gin
I0515 18:19:04.337561 139662491390080 resource_reader.py:50] system_path_file_exists:encoder_decoder.gin
E0515 18:19:04.337830 139662491390080 resource_reader.py:55] Path not found: encoder_decoder.gin
I0515 18:19:04.337974 139662491390080 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/encoder_decoder.gin
E0515 18:19:04.338099 139662491390080 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/encoder_decoder.gin
I0515 18:19:04.338801 139662491390080 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0515 18:19:04.339069 139662491390080 resource_reader.py:55] Path not found: decoder_only.gin 
I0515 18:19:04.339216 139662491390080 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
E0515 18:19:04.339390 139662491390080 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
I0515 18:19:04.362479 139662491390080 train.py:57] building model
Traceback (most recent call last):
  File "/opt/conda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/train.py", line 58, in main   
    model = Prior()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper     
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper     
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 527, in __init__  
    self.decoder = decoder_factory()
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 479, in __init__
    self.embedder = embedder()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 297, in __init__
    for n, p in model.encoder.rvq.named_buffers():
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_script.py", line 785, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'rvq'
  In call to configurable 'MultivariateEmbedding' (<class 'msprior.attention.MultivariateEmbedding'>)
  In call to configurable 'Decoder' (<class 'msprior.attention.Decoder'>)
  In call to configurable 'Prior' (<class 'msprior.attention.Prior'>)
```

The RAVE model was trained (I think) using this command:
```bash
rave train --config v2 --config causal --config spectral_discriminator --db_path /scratch/tim-music/r2_preprocessed --name r2_tim-music --gpu 0
```

**Comment by caillonantoine** [comment]
Hi ! Thanks for flagging this,
This comes from the flag `pretrained_embedding` which is only compatible with discrete models, I will include a warning ! In the meantime you can launch your training using 

```bash
msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music
```

(I switched encoder_decoder_continuous to decoder_only as the encoder_decoder_continuous relies on a model that isn't open source yet)

**Comment by timmb** [comment]
Ah yeah I see it on second reading of the readme. Thanks!

**Comment by timmb** [comment]
Wait, sorry, closed too soon!

I updated with your suggested command, and have a new error on training:

```bash
 msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music --gpu 0
```

Output:
```
I0515 18:43:11.830150 140596023464064 train.py:49] parsing configuration
I0515 18:43:11.830831 140596023464064 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0515 18:43:11.833477 140596023464064 resource_reader.py:55] Path not found: decoder_only.gin
I0515 18:43:11.833724 140596023464064 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
E0515 18:43:11.834538 140596023464064 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
I0515 18:43:11.842942 140596023464064 train.py:57] building model
Traceback (most recent call last):
  File "/opt/conda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/train.py", line 58, in main
    model = Prior()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 527, in __init__
    self.decoder = decoder_factory()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 479, in __init__
    self.embedder = embedder()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 295, in __init__
    model = torch.jit.load(from_pretrained).eval()
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_serialization.py", line 152, in load
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename None does not exist
  In call to configurable 'MultivariateEmbedding' (<class 'msprior.attention.MultivariateEmbedding'>)
  In call to configurable 'Decoder' (<class 'msprior.attention.Decoder'>)
  In call to configurable 'Prior' (<class 'msprior.attention.Prior'>)
```

**Comment by caillonantoine** [comment]
That's strange ! Can you run the following script and tell me if the same error appears ?

```python
import msprior.attention
import gin

gin.parse_config_file("decoder_only.gin")

model = msprior.attention.Prior()
```

**Comment by caillonantoine** [comment]
The first message was the one expected ! Update your msprior install (`pip install --upgrade acids-msprior`) and retry your training !

**Comment by timmb** [comment]
New error:

```
(base) root@ecf808e6ea2f:/workspace# msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music --gpu 0
I0515 19:18:09.736317 140216766775424 train.py:49] parsing configuration
I0515 19:18:09.736958 140216766775424 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0515 19:18:09.737540 140216766775424 resource_reader.py:55] Path not found: decoder_only.gin
I0515 19:18:09.737771 140216766775424 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
E0515 19:18:09.737969 140216766775424 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
I0515 19:18:09.753327 140216766775424 train.py:57] building model
Traceback (most recent call last):
  File "/opt/conda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/train.py", line 58, in main
    model = Prior()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 532, in __init__
    self.decoder = decoder_factory()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 484, in __init__
    self.embedder = embedder()
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/attention.py", line 299, in __init__
    if hasattr(model.encoder, "rvq"):
UnboundLocalError: local variable 'model' referenced before assignment
  In call to configurable 'MultivariateEmbedding' (<class 'msprior.attention.MultivariateEmbedding'>)
  In call to configurable 'Decoder' (<class 'msprior.attention.Decoder'>)
  In call to configurable 'Prior' (<class 'msprior.attention.Prior'>)
```

**Comment by caillonantoine** [comment]
Reupdate your install as soon as this [action is done running](https://github.com/caillonantoine/msprior/actions/runs/4984299624/jobs/8922442785)

**Comment by caillonantoine** [comment]
From what I understand the script is trying to load a pretrained model called "None", but I explicitly tell it not to load it if the value is None. Even weirder, the error isn't showing up on my server.
I'm gonna need you to clone the repo and manually test the project

```bash
git clone https://github.com/caillonantoine/msprior.git
cd msprior
pytest
```

an post the output here !

**Comment by timmb** [comment]
Tests pass.

```
(base) root@ecf808e6ea2f:/workspace/msprior/msprior/configs# git pull
Already up to date.
(base) root@ecf808e6ea2f:/workspace/msprior# pytest
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.10.8, pytest-7.3.1, pluggy-1.0.0
rootdir: /workspace/msprior
plugins: hypothesis-6.61.0
collected 25 items                                                                                                                                                                               

tests/test_attention.py .....                                                                                                                                                              [ 20%]
tests/test_cache.py ....                                                                                                                                                                   [ 36%]
tests/test_configs.py ................                                                                                                                                                     [100%]

====================================================================================== 25 passed in 37.50s =======================================================================================

**Comment by caillonantoine** [comment]
Found it !

It was a tricky one. [Next version of msprior](https://github.com/caillonantoine/msprior/actions/runs/4984516650) wiill fix that :)

**Comment by timmb** [comment]
Awesome thanks! Sorry definitely getting there but a new error:

```
msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music --gpu 0
I0515 19:57:54.112611 139805030903936 train.py:49] parsing configuration
I0515 19:57:54.114039 139805030903936 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0515 19:57:54.114439 139805030903936 resource_reader.py:55] Path not found: decoder_only.gin
I0515 19:57:54.114713 139805030903936 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
E0515 19:57:54.115027 139805030903936 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
I0515 19:57:54.125423 139805030903936 train.py:61] building model
I0515 19:57:54.476906 139805030903936 train.py:64] loading dataset
Traceback (most recent call last):
  File "/opt/conda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/train.py", line 71, in main
    train_loader = data.DataLoader(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

(I just reran the preprocessing with the new acids-msprior but that didn't make a difference.)

**Comment by caillonantoine** [comment]
The script cannot find your dataset, are you sure there isn't a typo ?

**Comment by timmb** [comment]
So my train command is
```bash
root@ecf808e6ea2f:/workspace/runs/r2_tim-music# msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess/ --name r2_tim-music --gpu 0
```

If I run
```bash
root@ecf808e6ea2f:/workspace/runs/r2_tim-music# ls -arfl /scratch/tim-music/msprior/preprocess/
```
I get
```
total 142572
drwxrwxrwx 1 root root      4096 May 15 19:56 .
drwxrwxrwx 1 root root      4096 May 15 15:26 ..
-rw-r--r-- 1 root root  19603456 May 15 19:57 data.mdb
-rw-r--r-- 1 root root      8192 May 15 19:57 lock.mdb
-rw-r--r-- 1 root root 126380161 May 15 19:56 r2_tim-music_incomplete.ts
```
which was created by the preprocess stage. Does this look right?

**Comment by timmb** [comment]
Ah ok, I set a breakpoint in train.py to find the issue. My dataset has length 2378 but the validation set is being set at size 8192 so there is nothing left for the training set

**Comment by caillonantoine** [comment]
You can set the validation size using `--val_size` during training, but it looks like your dataset is pretty small

**Comment by caillonantoine** [comment]
can you send me the `data.mdb` file ? (caillon [ at ] ircam.fr)

**Comment by timmb** [comment]
Sent. Thanks again for the help!

**Comment by caillonantoine** [comment]
There were many things that needed fixing, I'm glad it's done ! 
Upgrade your msprior, re-launch the preprocess and training, and you should be good to go.

**Comment by timmb** [comment]
Thanks Antoine. I've updated to 1.0.9. New error:

```
 msprior train --config decoder_only --db_path /scratch/tim-music/msprior/preprocess --name r2_tim-music --val_size 256 --gpu 0
I0515 21:38:00.252595 139767747072128 train.py:52] parsing configuration
I0515 21:38:00.253315 139767747072128 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0515 21:38:00.253675 139767747072128 resource_reader.py:55] Path not found: decoder_only.gin
I0515 21:38:00.253758 139767747072128 resource_reader.py:50] system_path_file_exists:/opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
E0515 21:38:00.253953 139767747072128 resource_reader.py:55] Path not found: /opt/conda/lib/python3.10/site-packages/msprior/decoder_only.gin
I0515 21:38:00.285503 139767747072128 train.py:64] loading dataset
I0515 21:38:00.302506 139767747072128 train.py:72] quantizer number retrieval
Traceback (most recent call last):
  File "/opt/conda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/msprior_scripts/train.py", line 75, in main
    f"NUM_QUANTIZERS={train[0]['decoder_inputs'].shape[-1]}")
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/opt/conda/lib/python3.10/site-packages/msprior/dataset.py", line 45, in __getitem__
    ae = self.task_fn(ae)
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/msprior/task.py", line 11, in decoder_only_rave
    start = randint(0, inputs[decoder_key].shape[0] - seq_len - 1)
  File "/opt/conda/lib/python3.10/random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "/opt/conda/lib/python3.10/random.py", line 353, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, 0, 0)
  In call to configurable 'decoder_only_rave' (<function decoder_only_rave at 0x7f1d50a5e320>)
```

**Comment by caillonantoine** [comment]
You have to repreprocess your dataset first :)

**Comment by timmb** [comment]
Yep that fixed it! Thanks!
