### ISSUE TITLE
Dataset too small when exporting msprior 

### ISSUE THREAD

**Issue by joystiller** [caillonantoine/msprior#10]
I run into an error when attempting to export an msprior model. It seem like the code is looking for .ckpt files, but no checkpoints are saved during training, because the training batches are smaller than the logging interval. As dataset I use 3 hours of audio (no audio sample shorter than 2-3 minutes). This all worked fine when I preprocess using rave, and I got 447 training batches, but the msprior training script shrinks it down to 5 % because the training batches are smaller than the validation size. Every little bit of help would be much appreciated! 

See code snippet from train.py here: 

```
    if FLAGS.val_size > len(dataset):
        logging.warn(
            r"Dataset too small, using 5% of the train set as the val set")
        FLAGS.val_size = len(dataset) // 20
```

Here is the output from the msprior preprocess: 

```
root@C.7440696:/workspace$ msprior preprocess --audio /workspace/audio --out_path /workspace/preprocessed-prior-audioset/ --rave /workspace/runs/test6_fded3c32dd/test6_fded3c32dd.ts 
Using chunks of 23.78s
Found 37 audio files in /workspace/audio
dataset length: 2:57:32.200635: : 0it [00:06, ?it/s]
root@C.7440696:/workspace$ 
```

And here is the output from the training.

```
I1106 21:13:34.080431 139890512257664 train.py:55] parsing configuration
I1106 21:13:34.080662 139890512257664 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E1106 21:13:34.081046 139890512257664 resource_reader.py:55] Path not found: decoder_only.gin
I1106 21:13:34.081120 139890512257664 resource_reader.py:50] system_path_file_exists:/content/miniconda/lib/python3.11/site-packages/msprior/decoder_only.gin
E1106 21:13:34.081209 139890512257664 resource_reader.py:55] Path not found: /content/miniconda/lib/python3.11/site-packages/msprior/decoder_only.gin
I1106 21:13:34.090517 139890512257664 train.py:67] loading dataset
W1106 21:13:34.090931 139890512257664 train.py:71] Dataset too small, using 5% of the train set as the val set
I1106 21:13:34.091561 139890512257664 train.py:81] quantizer number retrieval
I1106 21:13:34.092106 139890512257664 train.py:86] building model
I1106 21:13:35.128053 139890512257664 train.py:130] creating trainer
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
I1106 21:13:35.146692 139890512257664 train.py:143] launch training
/content/miniconda/lib/python3.11/site-packages/pytorch_lightning/loops/utilities.py:94: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type    | Params
------------------------------------
0 | decoder | Decoder | 43.4 M
------------------------------------
43.4 M    Trainable params
0         Non-trainable params
43.4 M    Total params
173.625   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/content/miniconda/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 192 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/content/miniconda/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 192 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/content/miniconda/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:1600: PossibleUserWarning: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=10). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 3:  33%|█████████████████████████████████████████                                                                                  | 2/6 [00:00<00:00,  9.94it/s, loss=6.91, v_num=3]^C/content/miniconda/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:48: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
```

And here is the msprior export:

```
streaming mode is set to True
W1106 15:26:02.451779 140189831291264 attention.py:370] pretrained_embedding is only compatible with discrete rave models, skiping
Traceback (most recent call last):
  File "/content/miniconda/bin/msprior", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/content/miniconda/lib/python3.11/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/content/miniconda/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/content/miniconda/lib/python3.11/site-packages/msprior_scripts/export.py", line 16, in main
    model = ScriptedPrior(
            ^^^^^^^^^^^^^^
  File "/content/miniconda/lib/python3.11/site-packages/msprior/scripted.py", line 43, in init
    ckpt = next(iter(ckpts))
           ^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by joystiller** [comment]
Error happened because I was pointing to the wrong .ts file. Instead, choose the .ts file that appears in the dataset folder during pre-process.
