### ISSUE TITLE
Error on training "

### ISSUE THREAD

**Issue by devstermarts** [caillonantoine/msprior#3]
Hi @caillonantoine, I'm currently running into a new error on msprior train. 

`#Training
%cd /content/drive/MyDrive/msprior/output/
!/content/miniconda/bin/msprior train \
--db_path /content/drive/MyDrive/msprior/processed \
--name trainingname`

Error log:

`I0607 14:34:52.512738 139873002992000 train.py:52] parsing configuration
I0607 14:34:52.513115 139873002992000 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0607 14:34:52.513501 139873002992000 resource_reader.py:55] Path not found: decoder_only.gin
I0607 14:34:52.513589 139873002992000 resource_reader.py:50] system_path_file_exists:/content/miniconda/lib/python3.9/site-packages/msprior/decoder_only.gin
E0607 14:34:52.513657 139873002992000 resource_reader.py:55] Path not found: /content/miniconda/lib/python3.9/site-packages/msprior/decoder_only.gin
I0607 14:34:52.529041 139873002992000 train.py:64] loading dataset
I0607 14:34:52.535753 139873002992000 train.py:72] quantizer number retrieval
Traceback (most recent call last):
  File "/content/miniconda/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.9/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/miniconda/lib/python3.9/site-packages/msprior_scripts/train.py", line 75, in main
    f"NUM_QUANTIZERS={train[0]['decoder_inputs'].shape[-1]}")
  File "/content/miniconda/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
IndexError: list index out of range`

Pytorch version is: pytorch-lightning-1.9.0

**Comment by caillonantoine** [comment]
Hi, I think this is related to a dataset size problem. I have pushed a [fix](https://github.com/caillonantoine/msprior/actions/runs/5413650303) that should solve it hopefully ! Let me know !

**Comment by ultranoise** [comment]
I am also following this issue because at the training with `msprior train --config recurrent` I get:

```
I0703 13:07:44.969008 4383540608 train.py:52] parsing configuration
I0703 13:07:44.969086 4383540608 resource_reader.py:50] system_path_file_exists:recurrent.gin
E0703 13:07:44.969213 4383540608 resource_reader.py:55] Path not found: recurrent.gin
I0703 13:07:44.969244 4383540608 resource_reader.py:50] system_path_file_exists:/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior/recurrent.gin
E0703 13:07:44.969269 4383540608 resource_reader.py:55] Path not found: /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior/recurrent.gin
I0703 13:07:44.969388 4383540608 resource_reader.py:50] system_path_file_exists:decoder_only.gin
E0703 13:07:44.969449 4383540608 resource_reader.py:55] Path not found: decoder_only.gin
I0703 13:07:44.969474 4383540608 resource_reader.py:50] system_path_file_exists:/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior/decoder_only.gin
E0703 13:07:44.969497 4383540608 resource_reader.py:55] Path not found: /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior/decoder_only.gin
I0703 13:07:44.974001 4383540608 train.py:64] loading dataset
I0703 13:07:44.974429 4383540608 train.py:72] quantizer number retrieval
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/bin/msprior", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior_scripts/main_cli.py", line 28, in main
    app.run(module.main)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/msprior_scripts/train.py", line 75, in main
    f"NUM_QUANTIZERS={train[0]['decoder_inputs'].shape[-1]}")
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
IndexError: list index out of range
```
preprocessed files are shared here: https://github.com/ultranoise/satoshiii/tree/main/preproc
